# CONFIG SIMULASI DEFI x BANK (ABM + Monte Carlo)

n_iterations: 1000
n_processes: 4
steps: 1000

agents:
  - class: BankAgent
    id: bank_eu
    params:
      capital: 800_000_000
      crypto_exposure: 0.02
      interest_rate: 0.02
  - class: BorrowerAgent
    id: borrower_eu
    params:
      risk_tolerance: 0.7
      loan_demand: 100000
  - class: ArbitrageurAgent
    id: arbitrageur_eu
    params:
      capital: 500_000

market_params:
  mu: 0.0
  sigma: 0.015
  jump_prob: 0.005
  jump_size: [-0.1, 0.1]
  shock_schedule: {}

scenarios:
  baseline:
    active: true
  depeg:
    active: false
  panic_selling:
    active: false
  cex_intervention:
    active: false
  imf_intervention:
    active: false
  combo:
    active: false
  climate:
    active: false

panic_threshold: 0.85


# data path / notes
notes:
  - Rasio inklusi keuangan 2021: 78% (contoh World Bank Findex)
  - Lending rate baseline: 8.62% (Bank Indonesia)
  - TVL DeFi global 2022–2025: 55 miliar USD
  - TVL Aave 2022–2025: diimpor dari csv (tvl_aave_2022_2025.csv)
  - Volume stablecoin per minggu: diimpor dari csv (volume_stablecoins_perweek.csv)

disclaimer: |
  File config ini adalah baseline; parameter dapat disesuaikan untuk masing-masing eksperimen atau validasi sensitivitas model.
