# CONFIG SIMULASI DEFI x BANK (ABM + Monte Carlo)

n_iterations: 1000
n_processes: 4
steps: 1000

agents:
  - class: BankAgent
    id: bank_1
    params:
      capital: 1000000000.0
      crypto_exposure: 0.02
      interest_rate: 0.085
  - class: BorrowerAgent
    id: borrower_1
    params:
      risk_tolerance: 0.7
      loan_demand: 100000
  - class: ArbitrageurAgent
    id: arbitrageur_1
    params:
      capital: 500000
  - class: CEXAgent
    id: cex_1
    params:
      reserve: 100000000.0
  - class: RegulatorAgent
    id: regulator_1
    params:
      liquidity_buffer: 200000000.0

market_params:
  mu: 0.0
  sigma: 0.02
  jump_prob: 0.01
  jump_size: [-0.1, 0.1]
  shock_schedule:
    50: 0.1  # shock di langkah ke-50 menurunkan harga stablecoin 10%
    200: 0.2 # shock di langkah ke-200 menurunkan harga stablecoin 20%

scenarios:
  baseline:
    active: true
  depeg:
    active: false
    coin: USDC
    magnitude: 0.1
    step: 100
  panic_selling:
    active: false
    threshold: 0.85
  cex_intervention:
    active: false
  imf_intervention:
    active: false
  combo:
    active: false
  climate:
    active: false
    magnitude: 0.05
    step: 400

panic_threshold: 0.85

# data path / notes
notes:
  - Rasio inklusi keuangan 2021: 78% (contoh World Bank Findex)
  - Lending rate baseline: 8.62% (Bank Indonesia)
  - TVL DeFi global 2022–2025: 55 miliar USD
  - TVL Aave 2022–2025: diimpor dari csv (tvl_aave_2022_2025.csv)
  - Volume stablecoin per minggu: diimpor dari csv (volume_stablecoins_perweek.csv)

disclaimer: |
  File config ini adalah baseline; parameter dapat disesuaikan untuk masing-masing eksperimen atau validasi sensitivitas model.
