n_iterations: 1000
n_processes: 4
steps: 1000

agents:
  - class: BankAgent
    id: bank_id
    params:
      capital: 600_000_000
      crypto_exposure: 0.02
      interest_rate: 0.085
  - class: BorrowerAgent
    id: borrower_id
    params:
      risk_tolerance: 0.7
      loan_demand: 100000
  - class: ArbitrageurAgent
    id: arbitrageur_id
    params:
      capital: 500_000

market_params:
  mu: 0.0
  sigma: 0.02
  jump_prob: 0.005
  jump_size: [-0.1, 0.1]
  shock_schedule: {}

scenarios:
  baseline:
    active: true
  depeg:
    active: false
  panic_selling:
    active: false
  cex_intervention:
    active: false
  imf_intervention:
    active: false
  combo:
    active: false
  climate:
    active: false

panic_threshold: 0.85
